services:
  fastapi:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env  # Load environment variables from the .env file
    environment:
      - MONGO_URI=mongodb+srv://${MONGO_USER}:${MONGO_PASS}@cluster0.jsp7h.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0 